import "./globals.css";
import { Inter } from "next/font/google";
import NavigationBar from "@/public/components/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VHackathon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-w-screen min-h-screen bg-gradient-to-b from-[#081428] via-[#13243c] to-[#243d5e]`}
      >
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
